extern const int SEED = 42;
extern const double RHO = 0.7;         // 权重挥发因子
extern const double R1 = 20;           // 超越gbest score
extern const double R2 = 12;           // 超越pbest score
extern const double R3 = 8;            // 都不超过但在T准则接受 score
extern const double RAND_D_MAX = 0.7;  // rand destroy max scope
extern const double RAND_D_MIN = 0.1;  // rand destroy min scope
extern const double WORST_D_MIN = 0.1; // worst destroy min scope
extern const double WORST_D_MAX = 0.5; // worst destroy max scope
extern const int REGRET_N = 5;         // 这个貌似没用到
extern const double PHI = 0.2;         // 